# Generated by Django 5.1.6 on 2025-02-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('模型', models.TextField()),
                ('名称', models.TextField()),
                ('类型', models.TextField()),
                ('上下文', models.TextField()),
                ('费用', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='ai_model',
        ),
    ]
