# Generated by Django 5.1.6 on 2025-02-19 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0002_models_delete_ai_model'),
    ]

    operations = [
        migrations.RenameField(
            model_name='models',
            old_name='上下文',
            new_name='context',
        ),
        migrations.RenameField(
            model_name='models',
            old_name='名称',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='models',
            old_name='模型',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='models',
            old_name='类型',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='models',
            old_name='费用',
            new_name='type',
        ),
    ]
