# Generated by Django 5.1.6 on 2025-02-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0003_remove_uploadedfile_uploader_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaresource',
            options={'ordering': ['-upload_time'], 'verbose_name': '媒体资源', 'verbose_name_plural': '媒体资源'},
        ),
        migrations.AddField(
            model_name='mediaresource',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='文件名'),
        ),
        migrations.AddField(
            model_name='mediaresource',
            name='file_size',
            field=models.IntegerField(default=0, verbose_name='文件大小(字节)'),
        ),
        migrations.AddField(
            model_name='mediaresource',
            name='file_type',
            field=models.CharField(choices=[('image', '图片'), ('audio', '音频'), ('video', '视频'), ('document', '文档'), ('other', '其他')], default='other', max_length=20, verbose_name='文件类型'),
        ),
        migrations.AddField(
            model_name='mediaresource',
            name='mime_type',
            field=models.CharField(default='application/octet-stream', max_length=100, verbose_name='MIME类型'),
        ),
        migrations.AlterField(
            model_name='mediaresource',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='文件'),
        ),
    ]
