# Generated by Django 5.1.6 on 2025-02-19 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0003_rename_上下文_models_context_rename_名称_models_cost_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='models',
            new_name='ModelInfo',
        ),
    ]
