# Generated by Django 5.1.6 on 2025-02-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0004_alter_mediaresource_options_mediaresource_file_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
