# Generated by Django 5.1.6 on 2025-02-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0004_rename_models_modelinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='配置名称')),
                ('config_type', models.CharField(choices=[('GLM', '智谱AI'), ('COZE', 'Coze'), ('QWEN', '通义千问')], max_length=20, verbose_name='配置类型')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API密钥')),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='模型名称')),
                ('model_id', models.CharField(blank=True, max_length=100, verbose_name='模型ID')),
                ('base_url', models.URLField(blank=True, verbose_name='基础URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'AI配置',
                'verbose_name_plural': 'AI配置',
            },
        ),
    ]
