# Generated by Django 5.1.6 on 2025-02-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0005_delete_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaresource',
            name='file_size',
            field=models.IntegerField(editable=False, verbose_name='文件大小(字节)'),
        ),
        migrations.AlterField(
            model_name='mediaresource',
            name='file_type',
            field=models.CharField(choices=[('image', '图片'), ('audio', '音频'), ('video', '视频'), ('document', '文档'), ('other', '其他')], editable=False, max_length=20, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='mediaresource',
            name='mime_type',
            field=models.CharField(editable=False, max_length=100, verbose_name='MIME类型'),
        ),
    ]
