# Generated by Django 5.1.6 on 2025-02-19 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0005_aiconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AIConfig',
        ),
    ]
