# Generated by Django 5.1.6 on 2025-02-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0006_alter_mediaresource_file_size_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='文件')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='文件名')),
                ('file_type', models.CharField(choices=[('image', '图片'), ('audio', '音频'), ('video', '视频'), ('document', '文档'), ('other', '其他')], editable=False, max_length=20, verbose_name='文件类型')),
                ('file_size', models.IntegerField(verbose_name='文件大小(字节)')),
                ('mime_type', models.CharField(max_length=100, verbose_name='MIME类型')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '上传文件',
                'verbose_name_plural': '上传文件',
                'db_table': 'uploaded_files',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='mediaresource',
            options={'verbose_name': '媒体资源', 'verbose_name_plural': '媒体资源'},
        ),
        migrations.RemoveField(
            model_name='mediaresource',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='mediaresource',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='mediaresource',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='mediaresource',
            name='mime_type',
        ),
        migrations.AlterField(
            model_name='mediaresource',
            name='file',
            field=models.FileField(upload_to='media/', verbose_name='文件'),
        ),
    ]
