# Generated by Django 5.1.6 on 2025-02-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0006_delete_aiconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelinfo',
            options={'verbose_name': 'AI-模型信息', 'verbose_name_plural': 'AI-模型信息'},
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='context',
            field=models.TextField(verbose_name='上下文'),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='cost',
            field=models.TextField(verbose_name='费用'),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='model',
            field=models.TextField(verbose_name='模型'),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='name',
            field=models.TextField(verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='type',
            field=models.TextField(verbose_name='类型'),
        ),
        migrations.AlterModelTable(
            name='modelinfo',
            table='AI模型信息',
        ),
    ]
