# Generated by Django 5.1.6 on 2025-02-20 14:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0007_uploadedfile_alter_mediaresource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.DeleteModel(
            name='MediaResource',
        ),
    ]
