# Generated by Django 5.1.6 on 2025-02-19 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0007_alter_modelinfo_options_alter_modelinfo_context_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelinfo',
            name='type',
            field=models.TextField(choices=[('chat', '大语言模型'), ('vision', '多模态专转化'), ('function', '功能模型')], default='chat', help_text='模型的主要功能', verbose_name='类型'),
        ),
    ]
