# Generated by Django 5.1.6 on 2025-02-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0008_alter_modelinfo_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelinfo',
            options={'verbose_name': 'AI模型信息', 'verbose_name_plural': 'AI模型信息'},
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='context',
            field=models.TextField(verbose_name='模型描述'),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='cost',
            field=models.TextField(verbose_name='费用说明'),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='model',
            field=models.TextField(verbose_name='模型标识'),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='name',
            field=models.TextField(verbose_name='模型名称'),
        ),
        migrations.AlterField(
            model_name='modelinfo',
            name='type',
            field=models.CharField(choices=[('chat', '大语言模型'), ('vision', '多模态模型'), ('function', '功能模型')], default='chat', max_length=20, verbose_name='模型类型'),
        ),
        migrations.AlterModelTable(
            name='modelinfo',
            table='ai_model_info',
        ),
    ]
